Traceback (most recent call last):
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for variable,figure in plot_level.items():
    display(figure)
    figure.savefig(f'graph/{variable}_test.png') # save in png format 
    figure.savefig(f'graph/{variable}_test.pdf') # save in pdf format 
    figure.savefig(f'graph/{variable}_test.svg') # save in svg format
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [11][0m, in [0;36m<cell line: 1>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mfor[39;00m variable,figure [38;5;129;01min[39;00m plot_level[38;5;241m.[39mitems():
[0;32m      2[0m     display(figure)
[1;32m----> 3[0m     [43mfigure[49m[38;5;241;43m.[39;49m[43msavefig[49m[43m([49m[38;5;124;43mf[39;49m[38;5;124;43m'[39;49m[38;5;124;43mgraph/[39;49m[38;5;132;43;01m{[39;49;00m[43mvariable[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m_test.png[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;66;03m# save in png format [39;00m
[0;32m      4[0m     figure[38;5;241m.[39msavefig([38;5;124mf[39m[38;5;124m'[39m[38;5;124mgraph/[39m[38;5;132;01m{[39;00mvariable[38;5;132;01m}[39;00m[38;5;124m_test.pdf[39m[38;5;124m'[39m) [38;5;66;03m# save in pdf format [39;00m
[0;32m      5[0m     figure[38;5;241m.[39msavefig([38;5;124mf[39m[38;5;124m'[39m[38;5;124mgraph/[39m[38;5;132;01m{[39;00mvariable[38;5;132;01m}[39;00m[38;5;124m_test.svg[39m[38;5;124m'[39m)

File [1;32m~\Anaconda3\envs\mf\lib\site-packages\matplotlib\figure.py:3046[0m, in [0;36mFigure.savefig[1;34m(self, fname, transparent, **kwargs)[0m
[0;32m   3042[0m     [38;5;28;01mfor[39;00m ax [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39maxes:
[0;32m   3043[0m         stack[38;5;241m.[39menter_context(
[0;32m   3044[0m             ax[38;5;241m.[39mpatch[38;5;241m.[39m_cm_set(facecolor[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnone[39m[38;5;124m'[39m, edgecolor[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnone[39m[38;5;124m'[39m))
[1;32m-> 3046[0m [38;5;28mself[39m[38;5;241m.[39mcanvas[38;5;241m.[39mprint_figure(fname, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\Anaconda3\envs\mf\lib\site-packages\matplotlib\backend_bases.py:2319[0m, in [0;36mFigureCanvasBase.print_figure[1;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[0;32m   2315[0m [38;5;28;01mtry[39;00m:
[0;32m   2316[0m     [38;5;66;03m# _get_renderer may change the figure dpi (as vector formats[39;00m
[0;32m   2317[0m     [38;5;66;03m# force the figure dpi to 72), so we need to set it again here.[39;00m
[0;32m   2318[0m     [38;5;28;01mwith[39;00m cbook[38;5;241m.[39m_setattr_cm([38;5;28mself[39m[38;5;241m.[39mfigure, dpi[38;5;241m=[39mdpi):
[1;32m-> 2319[0m         result [38;5;241m=[39m print_method(
[0;32m   2320[0m             filename,
[0;32m   2321[0m             facecolor[38;5;241m=[39mfacecolor,
[0;32m   2322[0m             edgecolor[38;5;241m=[39medgecolor,
[0;32m   2323[0m             orientation[38;5;241m=[39morientation,
[0;32m   2324[0m             bbox_inches_restore[38;5;241m=[39m_bbox_inches_restore,
[0;32m   2325[0m             [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   2326[0m [38;5;28;01mfinally[39;00m:
[0;32m   2327[0m     [38;5;28;01mif[39;00m bbox_inches [38;5;129;01mand[39;00m restore_bbox:

File [1;32m~\Anaconda3\envs\mf\lib\site-packages\matplotlib\backend_bases.py:1648[0m, in [0;36m_check_savefig_extra_args.<locals>.wrapper[1;34m(*args, **kwargs)[0m
[0;32m   1640[0m     _api[38;5;241m.[39mwarn_deprecated(
[0;32m   1641[0m         [38;5;124m'[39m[38;5;124m3.3[39m[38;5;124m'[39m, name[38;5;241m=[39mname, removal[38;5;241m=[39m[38;5;124m'[39m[38;5;124m3.6[39m[38;5;124m'[39m,
[0;32m   1642[0m         message[38;5;241m=[39m[38;5;124m'[39m[38;5;132;01m%(name)s[39;00m[38;5;124m() got unexpected keyword argument [39m[38;5;124m"[39m[38;5;124m'[39m
[0;32m   1643[0m                 [38;5;241m+[39m arg [38;5;241m+[39m [38;5;124m'[39m[38;5;124m"[39m[38;5;124m which is no longer supported as of [39m[38;5;124m'[39m
[0;32m   1644[0m                 [38;5;124m'[39m[38;5;132;01m%(since)s[39;00m[38;5;124m and will become an error [39m[38;5;124m'[39m
[0;32m   1645[0m                 [38;5;124m'[39m[38;5;132;01m%(removal)s[39;00m[38;5;124m'[39m)
[0;32m   1646[0m     kwargs[38;5;241m.[39mpop(arg)
[1;32m-> 1648[0m [38;5;28;01mreturn[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\Anaconda3\envs\mf\lib\site-packages\matplotlib\_api\deprecation.py:415[0m, in [0;36mdelete_parameter.<locals>.wrapper[1;34m(*inner_args, **inner_kwargs)[0m
[0;32m    405[0m     deprecation_addendum [38;5;241m=[39m (
[0;32m    406[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIf any parameter follows [39m[38;5;132;01m{[39;00mname[38;5;132;01m!r}[39;00m[38;5;124m, they should be passed as [39m[38;5;124m"[39m
[0;32m    407[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mkeyword, not positionally.[39m[38;5;124m"[39m)
[0;32m    408[0m     warn_deprecated(
[0;32m    409[0m         since,
[0;32m    410[0m         name[38;5;241m=[39m[38;5;28mrepr[39m(name),
[1;32m   (...)[0m
[0;32m    413[0m                  [38;5;28;01melse[39;00m deprecation_addendum,
[0;32m    414[0m         [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m--> 415[0m [38;5;28;01mreturn[39;00m func([38;5;241m*[39minner_args, [38;5;241m*[39m[38;5;241m*[39minner_kwargs)

File [1;32m~\Anaconda3\envs\mf\lib\site-packages\matplotlib\backends\backend_agg.py:541[0m, in [0;36mFigureCanvasAgg.print_png[1;34m(self, filename_or_obj, metadata, pil_kwargs, *args)[0m
[0;32m    494[0m [38;5;124;03m"""[39;00m
[0;32m    495[0m [38;5;124;03mWrite the figure to a PNG file.[39;00m
[0;32m    496[0m 
[1;32m   (...)[0m
[0;32m    538[0m [38;5;124;03m    *metadata*, including the default 'Software' key.[39;00m
[0;32m    539[0m [38;5;124;03m"""[39;00m
[0;32m    540[0m FigureCanvasAgg[38;5;241m.[39mdraw([38;5;28mself[39m)
[1;32m--> 541[0m [43mmpl[49m[38;5;241;43m.[39;49m[43mimage[49m[38;5;241;43m.[39;49m[43mimsave[49m[43m([49m
[0;32m    542[0m [43m    [49m[43mfilename_or_obj[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mbuffer_rgba[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mpng[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43morigin[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mupper[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m    543[0m [43m    [49m[43mdpi[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfigure[49m[38;5;241;43m.[39;49m[43mdpi[49m[43m,[49m[43m [49m[43mmetadata[49m[38;5;241;43m=[39;49m[43mmetadata[49m[43m,[49m[43m [49m[43mpil_kwargs[49m[38;5;241;43m=[39;49m[43mpil_kwargs[49m[43m)[49m

File [1;32m~\Anaconda3\envs\mf\lib\site-packages\matplotlib\image.py:1675[0m, in [0;36mimsave[1;34m(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)[0m
[0;32m   1673[0m pil_kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mformat[39m[38;5;124m"[39m, [38;5;28mformat[39m)
[0;32m   1674[0m pil_kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mdpi[39m[38;5;124m"[39m, (dpi, dpi))
[1;32m-> 1675[0m image[38;5;241m.[39msave(fname, [38;5;241m*[39m[38;5;241m*[39mpil_kwargs)

File [1;32m~\Anaconda3\envs\mf\lib\site-packages\PIL\Image.py:2297[0m, in [0;36mImage.save[1;34m(self, fp, format, **params)[0m
[0;32m   2295[0m         fp [38;5;241m=[39m builtins[38;5;241m.[39mopen(filename, [38;5;124m"[39m[38;5;124mr+b[39m[38;5;124m"[39m)
[0;32m   2296[0m     [38;5;28;01melse[39;00m:
[1;32m-> 2297[0m         fp [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mw+b[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m   2299[0m [38;5;28;01mtry[39;00m:
[0;32m   2300[0m     save_handler([38;5;28mself[39m, fp, filename)

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'graph/PAKCCEMISCO2TKN_test.png'
FileNotFoundError: [Errno 2] No such file or directory: 'graph/PAKCCEMISCO2TKN_test.png'

