Traceback (most recent call last):
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ibhan\Anaconda3\envs\mf\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
baseline_first  = pd.concat([smalldata,parameters_melted],axis=1) # the original data plus the parameters 
baseline_first  = msmallmodel.insertModelVar(baseline_first) # to make sure all modelvariable are in the dataframe 
baseline_first.head().T # show the result, transposed
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [17][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m baseline_first  [38;5;241m=[39m pd[38;5;241m.[39mconcat([smalldata,[43mparameters_melted[49m],axis[38;5;241m=[39m[38;5;241m1[39m) [38;5;66;03m# the original data plus the parameters [39;00m
[0;32m      2[0m baseline_first  [38;5;241m=[39m msmallmodel[38;5;241m.[39minsertModelVar(baseline_first) [38;5;66;03m# to make sure all modelvariable are in the dataframe [39;00m
[0;32m      3[0m baseline_first[38;5;241m.[39mhead()[38;5;241m.[39mT

[1;31mNameError[0m: name 'parameters_melted' is not defined
NameError: name 'parameters_melted' is not defined

